# -*- coding: utf-8 -*-
"""console.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zOGH500fsmN_WcFHwBtpvDhGlCA1OjkL
"""

# from google.colab import drive
# drive.mount('/content/drive')
# %cd /content/drive/My Drive/Colab Notebooks/ukp

# !pip install -q --upgrade ipython
# !pip install -q --upgrade ipykernel

!pip install -r requirements.txt

# !pip install tensorflow --upgrade --force-reinstall

"""#run model"""

# %cd /content/drive/My Drive/Colab Notebooks/ukp
!python3 Train_POS.py

# %cd /content/drive/My Drive/Colab Notebooks/ukp
!python3 Save_and_Load.py models/sentiment2_0.2429_0.2640_35.h5

# %cd /content/drive/My Drive/Colab Notebooks/ukp
!python3 RunModel_CoNLL_Format.py models/1-sentiment2_0.3279_0.2670_19.h5 poems/ger1/dev.conll dev1.tsv